name: Deploy Supabase Migrations

on:
  push:
    branches:
      - main # Trigger on push events to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: migrate

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to project
        run: SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }} supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}

      # Apply Supabase migrations using the production database URL secret
      - name: Apply Supabase migrations
        run: SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }} supabase db push
